### ISSUE TITLE
srcDir assets does not exist

### ISSUE THREAD

**Issue by dustinfarris** [joostdevries/twiddle-backend#13]
I tried building a docker container based on included Dockerfile.

When running build-addon.sh, it exits with this error (running ember build):

```
Build failed.
The Broccoli Plugin: [Funnel] failed with:
Error: You specified a `"srcDir": assets` which does not exist and did not specify `"allowEmpty": true`.
```

It's true there is no assets directory anywhere.  Where is this supposed to come from?

**Comment by Gaurav0** [comment]
allowEmpty is now true.
