### ISSUE TITLE
Addon build should include addon-test-support folder

### ISSUE THREAD

**Issue by code0100fun** [joostdevries/twiddle-backend#23]
Using an addon like [ember-native-dom-helpers](https://github.com/cibernox/ember-native-dom-helpers) for integration tests does not work because the helpers live in `/addon-test-support`. The contents of this folder do not appear in the final `addon.js` output.

Here's a quick [twiddle](https://ember-twiddle.com/58027e0abcdbda5ee6001ce01245eac5?openFiles=tests.integration.components.my-component-test.js%2Ctemplates.components.my-component.hbs) that has an integration test with the desired import commented out at the top.

**Comment by san650** [comment]
This issue seems to be related to #28

**Comment by Gaurav0** [comment]
Should be fixed
